name: CI/CD Pipeline - Microservice Conversion Financière

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    NODE_VERSION: "18.x"

jobs:
    # Job 1: Tests et Validation
    test-and-validate:
        runs-on: ubuntu-latest
        name: Tests et Validation

        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: Installation des dépendances
              run: npm ci

            - name: Exécution des tests
              run: npm test

            - name: Génération du rapport de couverture
              run: npm run test:coverage

            - name: Vérification du seuil de couverture
              run: npm run coverage:check

            - name: Archive du rapport de couverture
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: coverage/
                  retention-days: 7

            - name: Audit de sécurité
              run: npm audit --audit-level=moderate

    # Job 2: Build et Préparation
    build:
        runs-on: ubuntu-latest
        needs: test-and-validate
        name: Build et Préparation

        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: Installation des dépendances de production
              run: npm ci --production

            - name: Test de démarrage
              run: |
                  # Démarrage en arrière-plan sur un port spécifique
                  PORT=3001 NODE_ENV=test timeout 15s node index.js &
                  APP_PID=$!

                  # Attente du démarrage
                  sleep 5

                  # Test de santé avec retry
                  for i in {1..5}; do
                    if curl -f "http://localhost:3001/health" >/dev/null 2>&1; then
                      echo "✅ Service démarre correctement"
                      break
                    elif [ $i -eq 5 ]; then
                      echo "❌ Service ne démarre pas correctement après 5 tentatives"
                      exit 1
                    else
                      echo "Tentative $i/5 - En attente..."
                      sleep 2
                    fi
                  done

                  # Arrêt propre du processus
                  kill $APP_PID 2>/dev/null || true
                  wait $APP_PID 2>/dev/null || true

            - name: Nettoyage final des processus
              run: |
                  # Nettoyage de tous les processus Node.js restants
                  pkill -f "node.*index.js" 2>/dev/null || true
                  sleep 2

            - name: Création de l'artifact de déploiement
              run: |
                  # Création d'un répertoire temporaire propre
                  BUILD_DIR="/tmp/financial-microservice-build"
                  rm -rf "$BUILD_DIR"
                  mkdir -p "$BUILD_DIR"

                  # Copie sélective des fichiers nécessaires
                  echo "📁 Copie des fichiers essentiels..."
                  cp package.json "$BUILD_DIR/"
                  cp index.js "$BUILD_DIR/"
                  cp -r src/ "$BUILD_DIR/" 2>/dev/null || true
                  cp ecosystem.config.js "$BUILD_DIR/" 2>/dev/null || true
                  cp README.md "$BUILD_DIR/" 2>/dev/null || true

                  # Création de l'archive depuis le répertoire de build
                  cd "$BUILD_DIR"
                  tar -czf "/tmp/financial-microservice-${{ github.sha }}.tar.gz" .

                  # Copie vers le workspace
                  cp "/tmp/financial-microservice-${{ github.sha }}.tar.gz" "$GITHUB_WORKSPACE/"

                  echo "✅ Artifact créé: financial-microservice-${{ github.sha }}.tar.gz"

            - name: Upload de l'artifact
              uses: actions/upload-artifact@v4
              with:
                  name: financial-microservice-${{ github.sha }}
                  path: financial-microservice-${{ github.sha }}.tar.gz
                  retention-days: 30

    # Job 3: Déploiement en Staging
    deploy-staging:
        runs-on: ubuntu-latest
        needs: [test-and-validate, build]
        name: Déploiement Staging
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: financial-microservice-${{ github.sha }}

            - name: Transfer artifact to staging server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.STAGING_HOST }}
                  username: ${{ secrets.STAGING_USER }}
                  key: ${{ secrets.STAGING_SSH_KEY }}
                  port: ${{ secrets.STAGING_PORT }}
                  source: "financial-microservice-${{ github.sha }}.tar.gz"
                  target: "/tmp/"

            - name: Deploy to staging server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.STAGING_HOST }}
                  username: ${{ secrets.STAGING_USER }}
                  key: ${{ secrets.STAGING_SSH_KEY }}
                  port: ${{ secrets.STAGING_PORT }}
                  timeout: 30s
                  command_timeout: 10m
                  script: |
                      echo "🔑 SSH connection successful!"
                      echo "🏠 Current directory: $(pwd)"
                      echo "👤 Current user: $(whoami)"

                      # Check prerequisites
                      echo "🔍 Checking prerequisites..."
                      which node || (echo "❌ Node.js not found. Installing..." && curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs)
                      which npm || echo "❌ npm not found"
                      which pm2 || (echo "📦 Installing PM2..." && sudo npm install -g pm2)

                      echo "📁 Setting up application directory..."
                      sudo mkdir -p /var/www/financial-microservice/{releases,shared/logs,shared/config}
                      sudo chown -R $(whoami):$(whoami) /var/www/financial-microservice

                      # Create release directory
                      VERSION=$(date +%Y%m%d_%H%M%S)
                      RELEASE_DIR="/var/www/financial-microservice/releases/$VERSION"
                      mkdir -p "$RELEASE_DIR"

                      echo "📦 Preparing staging release $VERSION..."

                      # Extract uploaded artifact
                      echo "📥 Extracting deployment artifact..."
                      if [ -f "/tmp/financial-microservice-${{ github.sha }}.tar.gz" ]; then
                          tar -xzf /tmp/financial-microservice-${{ github.sha }}.tar.gz -C "$RELEASE_DIR"
                          echo "✅ Staging artifact extracted successfully"
                      else
                          echo "❌ Artifact not found at /tmp/financial-microservice-${{ github.sha }}.tar.gz"
                          exit 1
                      fi

                      cd "$RELEASE_DIR"

                      # Install dependencies
                      echo "📚 Installing dependencies..."
                      npm ci --production --silent

                      # Stop old application
                      echo "⏹️ Stopping old staging application..."
                      pm2 stop financial-microservice-staging 2>/dev/null || echo "No previous staging app found"
                      pm2 delete financial-microservice-staging 2>/dev/null || echo "No previous staging app to delete"

                      # Update symlink
                      echo "🔗 Updating symlink..."
                      rm -f /var/www/financial-microservice/current
                      ln -sf "$RELEASE_DIR" /var/www/financial-microservice/current

                      # Start application with PM2
                      echo "🚀 Starting staging application..."
                      cd /var/www/financial-microservice/current

                      # Start with environment variables
                      PORT=3000 NODE_ENV=staging pm2 start index.js --name financial-microservice-staging
                      pm2 save

                      # Wait for startup
                      echo "⏳ Waiting for application to start..."
                      sleep 10

                      # Health check
                      echo "🩺 Performing health check..."
                      if curl -f http://localhost:3000/health >/dev/null 2>&1; then
                          echo "✅ Staging application is healthy!"
                      else
                          echo "❌ Health check failed"
                          pm2 logs financial-microservice-staging --lines 20
                          exit 1
                      fi

                      echo "✅ Staging deployment completed successfully!"
                      echo "📊 PM2 Status:"
                      pm2 status

                      # Cleanup old releases (keep last 3)
                      echo "🧹 Cleaning up old releases..."
                      cd /var/www/financial-microservice/releases
                      ls -t | tail -n +4 | xargs -r rm -rf

            - name: Tests de santé post-déploiement
              run: |
                  sleep 30
                  curl -f "${{ secrets.STAGING_URL }}/health"
                  curl -f "${{ secrets.STAGING_URL }}/convert?from=EUR&to=USD&amount=100"

    # Job 4: Déploiement en Production
    deploy-production:
        runs-on: ubuntu-latest
        needs: [test-and-validate, build]
        name: Déploiement Production
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: financial-microservice-${{ github.sha }}

            - name: Transfer artifact to production server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.PRODUCTION_HOST }}
                  username: ${{ secrets.PRODUCTION_USER }}
                  key: ${{ secrets.PRODUCTION_SSH_KEY }}
                  port: ${{ secrets.PRODUCTION_PORT }}
                  source: "financial-microservice-${{ github.sha }}.tar.gz"
                  target: "/tmp/"

            - name: Deploy to production server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.PRODUCTION_HOST }}
                  username: ${{ secrets.PRODUCTION_USER }}
                  key: ${{ secrets.PRODUCTION_SSH_KEY }}
                  port: ${{ secrets.PRODUCTION_PORT }}
                  timeout: 30s
                  command_timeout: 10m
                  script: |
                      echo "🔑 SSH connection successful!"
                      echo "🏠 Current directory: $(pwd)"
                      echo "👤 Current user: $(whoami)"

                      # Check prerequisites
                      echo "🔍 Checking prerequisites..."
                      which node || (echo "❌ Node.js not found. Installing..." && curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs)
                      which npm || echo "❌ npm not found"
                      which pm2 || (echo "📦 Installing PM2..." && sudo npm install -g pm2)

                      echo "📁 Setting up application directory..."
                      sudo mkdir -p /var/www/financial-microservice/{releases,shared/logs,shared/config}
                      sudo chown -R $(whoami):$(whoami) /var/www/financial-microservice

                      # Create release directory
                      VERSION=$(date +%Y%m%d_%H%M%S)
                      RELEASE_DIR="/var/www/financial-microservice/releases/$VERSION"
                      mkdir -p "$RELEASE_DIR"

                      echo "📦 Preparing production release $VERSION..."

                      # Extract uploaded artifact
                      echo "📥 Extracting deployment artifact..."
                      if [ -f "/tmp/financial-microservice-${{ github.sha }}.tar.gz" ]; then
                          tar -xzf /tmp/financial-microservice-${{ github.sha }}.tar.gz -C "$RELEASE_DIR"
                          echo "✅ Production artifact extracted successfully"
                      else
                          echo "❌ Artifact not found at /tmp/financial-microservice-${{ github.sha }}.tar.gz"
                          exit 1
                      fi

                      cd "$RELEASE_DIR"

                      # Install dependencies
                      echo "📚 Installing dependencies..."
                      npm ci --production --silent

                      # Stop old application
                      echo "⏹️ Stopping old production application..."
                      pm2 stop financial-microservice-production 2>/dev/null || echo "No previous production app found"
                      pm2 delete financial-microservice-production 2>/dev/null || echo "No previous production app to delete"

                      # Update symlink
                      echo "🔗 Updating symlink..."
                      rm -f /var/www/financial-microservice/current
                      ln -sf "$RELEASE_DIR" /var/www/financial-microservice/current

                      # Start application with PM2
                      echo "🚀 Starting production application..."
                      cd /var/www/financial-microservice/current

                      # Start with environment variables
                      PORT=3001 NODE_ENV=production pm2 start index.js --name financial-microservice-production
                      pm2 save

                      # Wait for startup
                      echo "⏳ Waiting for application to start..."
                      sleep 10

                      # Health check
                      echo "🩺 Performing health check..."
                      if curl -f http://localhost:3001/health >/dev/null 2>&1; then
                          echo "✅ Production application is healthy!"
                      else
                          echo "❌ Health check failed"
                          pm2 logs financial-microservice-production --lines 20
                          exit 1
                      fi

                      echo "✅ Production deployment completed successfully!"
                      echo "📊 PM2 Status:"
                      pm2 status

                      # Cleanup old releases (keep last 3)
                      echo "🧹 Cleaning up old releases..."
                      cd /var/www/financial-microservice/releases
                      ls -t | tail -n +4 | xargs -r rm -rf

            - name: Tests de santé post-déploiement
              run: |
                  sleep 30
                  curl -f "${{ secrets.PRODUCTION_URL }}/health"
                  curl -f "${{ secrets.PRODUCTION_URL }}/convert?from=EUR&to=USD&amount=100"
